export default {
	anime: 'a[href^="#"], a[href="/s"]',
	animenocontext: 'a[href="/s"]',
	animesuggest: 'a[href="#s"]',
	awwnime: 'a[href^="#"]',
	chibi: 'a[href^="#"]]',
	esdeath: 'a[href^="#"]',
	fatestaynight: 'a[href^="#"]',
	gamindustri: 'a[href^="#"]',
	k_on: 'a[href="/s"]',
	kancolle: 'a[href^="#"]',
	kanmusu: 'a[href^="#"]',
	kanmusunights: 'a[href^="#"]',
	karanokyoukai: 'a[href^="#"]',
	kemonomimi: 'a[href^="#"]',
	leagueoflegends: 'a[href^="#"]',
	lovelive: 'a[href^="#"]',
	madokamagica: 'a[href^="#"], a[href="/a"], a[href="/g"], a[href="/m"], a[href="/s"]',
	manga: 'a[href^="//#"], a[href="/s"]',
	moescape: 'a[href^="#"]',
	nisekoi: 'a[href^="#"]',
	onetruebiribiri: 'a[href^="#"]',
	onetrueidol: 'a[href^="#"]',
	onetruetohsaka: 'a[href^="#"]',
	pantsu: 'a[href^="#"]',
	patchuu: 'a[href^="#"]',
	saber: 'a[href^="#"]',
	schoolidolfestival: 'a[href^="#"]',
	supersonico: 'a[href^="#"]',
	twodeeart: 'a[href^="#"]',
	visualnovels: 'a[href^="#"]',
};
